#include<stdio.h>
#include<conio.h>
main(){
	int i,j,k;
	for(i=1;i<=5;i++){
		for(j=1;j<=i;j++){
			printf("%d\t",i);
		}
		for(k=4;k>=i;k--){
			printf("\t");
		}
		for(k=4;k>=i;k--){
			printf("\t");
		}
		for(j=1;j<=i;j++){
			printf("%d\t",i);
		}
		printf("\n\n");
	}
}
